<!DOCTYPE html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>Php with google maps</title>
    <style>
        #map{
            height: 100%;
        }
        html,body{
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
</head>

<html>
<body>
<div id="map"></div>
<script>
    var customLabel = {
        monument:{
            label: 'M'
        },
        building:{
            label: 'B'
        }
    };

    function initMap(){
        var map = new google.maps.Map(document.getElementById('map'),{
            center: new google.maps.LatLng(47.0245117, 28.8322923),
            zoom: 9
        });
        var infoWindow = new google.maps.InfoWindow;

        downloadUrl('http://localhost/userregistration/SQL/xml.php',function(data){
            var xml = data.responseXML;
            var markers = xml.documentElement.getElementsByTagName('marker');
            Array.prototype.forEach.call(markers, function (markerElem){
                var id = markerElem.getAttribute('id');
                var name = markerElem.getAttribute('name');
                var address = markerElem.getAttribute('address');
                var type = markerElem.getAttribute('type');
                var point = new google.maps.LatLng(
                    parseFloat(markerElem.getAttribute('lat')),
                    parseFloat(markerElem.getAttribute('lng')));

                var infowincontent = document.createElement('div');
                var strong = document.createElement('strong');
                strong.textContent = name;
                infowincontent.appendChild(strong);
                infowincontent.appendChild(document.createElement('br'));

                var text = document.createElement('text');
                text.textContent = address
                infowincontent.appendChild(text);
                var icon = customLabel[type] || {};
                var marker = new google.maps.Marker({
                    map: map,
                    position: point,
                    label: icon.label
                });
                marker.addListener('click', function (){
                    infoWindow.setContent(infowincontent);
                    infoWindow.open(map, marker);
                });
            });
        });
    }

    function downloadUrl(url, callback){
        var request = window.ActiveXObject ?
            new ActiveXObject('Microsoft.XMLHTTP'):
            new XMLHttpRequest;

        request.onreadystatechange = function (){
            if(request.readyState == 4){
                request.onreadystatechange = doNothing;
                callback(request, request.status);
            }
        };

        request.open('GET', url, true);
        request.send(null);
    }
    function doNothing(){}

</script>

<script
    async src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyA43zMht60OalNkHOEp-nOy55SjuwWMD3c&callback=initMap&v=weekly">
</script>
</body>
</html>